[package]
name = "app"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
futures-util = "0.3.25"
hyper = { version = "0.14.23", features = ["full"] } 
tokio = { version = "1.24.1", features = ["full"] }
core = { path = "core" }
